version: "2"
services:
  # --------------------------------------------------------------------------------
  # DB Server
  # --------------------------------------------------------------------------------
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  # --------------------------------------------------------------------------------
  # Web Server
  # --------------------------------------------------------------------------------
  web: &app
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0", "-e", "development"]
    ports:
      - 13008:3000
    links:
      - db
      - cache
    depends_on:
      - db
      - cache
    volumes:
      - ".:/app:cached"
      - bundle_install:/usr/local/bundle
    stdin_open: true
    tty: true
  # --------------------------------------------------------------------------------
  # Webpack
  # --------------------------------------------------------------------------------
  webpack:
    <<: *app
    command: "bin/webpack-dev-server"
    ports:
      - "3035:3035"
    depends_on:
      - web
    tty: false
    stdin_open: false
  # --------------------------------------------------------------------------------
  # Redis
  # --------------------------------------------------------------------------------
  # cache:
  #   image: redis:3.2.9-alpine
  cache:
    build:
      context: .
      dockerfile: docker/cache/Dockerfile
  # --------------------------------------------------------------------------------
  # Worker
  # --------------------------------------------------------------------------------
  worker:
    <<: *app
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - db
      - cache
volumes:
  bundle_install:
    driver: local