version: "2"
services:
  # --------------------------------------------------------------------------------
  # DB Server
  # --------------------------------------------------------------------------------
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  # --------------------------------------------------------------------------------
  # Web Server
  # --------------------------------------------------------------------------------
  web: &app
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0 -e development"
    ports:
      - 13008:3000
    links:
      - db
      - cache
    depends_on:
      - db
      - cache
    volumes:
      - ".:/app:cached"
    stdin_open: true
    tty: true
  # --------------------------------------------------------------------------------
  # Redis
  # --------------------------------------------------------------------------------
  # cache:
  #   image: redis:3.2.9-alpine
  cache:
    build:
      context: .
      dockerfile: docker/cache/Dockerfile
  # --------------------------------------------------------------------------------
  # Worker
  # --------------------------------------------------------------------------------
  worker:
    <<: *app
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - db
      - cache