AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { }
#CheckSaveReturnValueCheck: { }
#CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
IsolateSeedDataCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck: { }
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 3 }
MoveFinderToNamedScopeCheck: { }
MoveModelLogicIntoModelCheck: { use_count: 5 }
NeedlessDeepNestingCheck: { nested_count: 4 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
# NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 3 }
# ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
RemoveUnusedMethodsInControllersCheck: { except_methods: [
  'ApplicationController#response_success',
  'ApplicationController#response_bad_request',
  'ApplicationController#response_unauthorized',
  'ApplicationController#response_not_found',
  'ApplicationController#response_conflict',
  'ApplicationController#response_internal_server_error',
  'Api::V1::GithubAppsController#webhook',
  'Reviewees::RegistrationsController#after_sign_up_path_for',
  'Reviewees::RegistrationsController#sign_up_params',
  'Reviewees::RegistrationsController#update_resource',
  'Reviewees::RegistrationsController#after_update_path_for',
  'Reviewees::RegistrationsController#after_inactive_sign_up_path_for',
  'Reviewees::ConfirmationsController#after_confirmation_path_for',
  'Reviewees::SessionsController#sso',
  'Reviewers::ConfirmationsController#after_confirmation_path_for',
  'Reviewers::RegistrationsController#after_sign_up_path_for',
  'Reviewers::RegistrationsController#sign_up_params',
  'Reviewers::RegistrationsController#after_inactive_sign_up_path_for',
  'Reviewers::SessionsController#sso',
  'ErrorsController#not_found',
  'ErrorsController#internal_server_error',
  'ApplicationController#routing_error',
  'Reviewers::SessionsController#after_sign_out_path_for',
  'Webhooks::GithubAppsController#handle'
] }
RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
RemoveUnusedMethodsInModelsCheck: { except_methods: [] }
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: { }
RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: { }
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }