api:
  github:
    headers:
      accept: application/vnd.github.machine-man-preview+json
    installation_url: https://api.github.com/installations/
    get_repositories_via_installation_url: https://api.github.com/installations/repositories
github:
  web_domain: https://github.com/
  api_domain: api.github.com
  request:
    access_token_uri: https://api.github.com/installations/<%= ENV['GITHUB_APP_INSTALLATION_ID'] %>/access_tokens
    header:
      accept: application/vnd.github.machine-man-preview+json
review_comments:
  max_working_hours: 30
reviews:
  body: PullRequestへようこそ！私はあなたにインラインでいくつかのコメントを残しました。
    ほとんどはスタイルを改善するコメントですが、コメントをさらに主観的にするため開発中です。
    インラインで問題に返信してもらったり、特定のタイプのフィードバックを多かれ少なかれ見たいと思ったらお知らせください。
