reviews:
  body: PullRequestへようこそ！私はあなたにインラインでいくつかのコメントを残しました。
    ほとんどはスタイルを改善するコメントですが、コメントをさらに主観的にするため開発中です。
    インラインで問題に返信してもらったり、特定のタイプのフィードバックを多かれ少なかれ見たいと思ったらお知らせください。
github:
  web_domain: https://github.com/
site:
  name: Mergee
  page_title: Mergee
  page_description: コードレビューのマーケットプレイス
  page_keywords: プルリクエスト、pullrequest、レビュー、エンジニア、独学、個人
  meta:
    ogp:
      type: 'website'
      image_path: 'top'
contents:
  prohibited_folders: ['vendor', 'public', 'log', 'node_modules', 'tmp', 'coverage', 'images']
  prohibited_files:
    basenames: ['DS_Store']
    extnames: ['.jpg', '.png', '.jpeg', '.gif', '.pdf']
rewards:
  price: 10

