api:
  github:
    headers:
      accept: application/vnd.github.machine-man-preview+json
    installation_url: https://api.github.com/installations/
    get_repositories_via_installation_url: https://api.github.com/installations/repositories
github:
  web_domain: https://github.com/
  api_domain: https://api.github.com/
  request:
    access_token_uri: https://api.github.com/installations/
    header:
      accept: application/vnd.github.machine-man-preview+json
review_comments:
  max_working_hours: 30
reviews:
  body: PullRequestへようこそ！私はあなたにインラインでいくつかのコメントを残しました。
    ほとんどはスタイルを改善するコメントですが、コメントをさらに主観的にするため開発中です。
    インラインで問題に返信してもらったり、特定のタイプのフィードバックを多かれ少なかれ見たいと思ったらお知らせください。
qiita:
  about_install_github_app: https://qiita.com/k_s/private/3b5354aab17edc6af33a
site:
  name: PushRequest
  page_title: PushRequest
  page_description: コードレビューのマーケットプレイス
  page_keywords: プルリクエスト、pullrequest、レビュー、エンジニア、独学、個人
  meta:
    ogp:
      type: 'website'
      image_path: 'top'
