top: http://<%= ENV['WEB_DOMAIN'] %>/
reviewers:
  top: http://<%= ENV['REVIEWER_DOMAIN'] %>/
  dashboard: http://<%= ENV['REVIEWER_DOMAIN'] %>/reviewers/dashboard
  sessions:
    new: http://<%= ENV['REVIEWER_DOMAIN'] %>/reviewers/sign_in
  pulls:
    show: http://<%= ENV['REVIEWER_DOMAIN'] %>/reviewers/pulls/
reviewees:
  dashboard: http://<%= ENV['WEB_DOMAIN'] %>/reviewees/dashboard
links:
  home: http://<%= ENV['WEB_DOMAIN'] %>
  reviewer_repo_show: http://<%= ENV['REVIEWER_DOMAIN'] %>/reviewers/repos/
