meta:
  site:
    name: CodeReview β
    page_title: CodeReview β
    page_description: 個人のためのコードレビューサービス
    page_keywords: コードレビュー、エンジニア、ソーシャルコーディング
og:
  title: CodeReview β
  type: website
  image: /og.png
