top: https://<%= ENV['WEB_DOMAIN'] %>/
reviewers:
  sessions:
    new: http://<%= ENV['REVIEWER_DOMAIN'] %>/reviewers/sign_in
  pulls:
    show: https://<%= ENV['WEB_DOMAIN'] %>/reviewers/pulls/
reviewees:
  memberships:
    join: http://<%= ENV['WEB_DOMAIN'] %>/reviewees/memberships/join?
links:
  home: https://<%= ENV['WEB_DOMAIN'] %>
  reviewer_repo_show: https://<%= ENV['WEB_DOMAIN'] %>/reviewers/repos/
