top: https://<%= ENV['WEB_DOMAIN'] %>/
reviewers:
  pulls:
    show: https://<%= ENV['WEB_DOMAIN'] %>/reviewers/pulls/
reviewees:
  memberships:
    join: http://<%= ENV['WEB_DOMAIN'] %>/reviewees/memberships/join?
links:
  home: https://<%= ENV['WEB_DOMAIN'] %>
  reviewer_pull_show_before: https://<%= ENV['WEB_DOMAIN'] %>/reviewers/pulls/
  reviewer_pull_show_after: /reviews/view_check
