top: https://<%= ENV['WEB_DOMAIN'] %>/
reviewers:
  top: https://<%= ENV['REVIEWER_DOMAIN'] %>/
  dashboard: https://<%= ENV['REVIEWER_DOMAIN'] %>/reviewers/dashboard
  sessions:
    new: http://<%= ENV['REVIEWER_DOMAIN'] %>/reviewers/sign_in
  pulls:
    show: https://<%= ENV['REVIEWER_DOMAIN'] %>/reviewers/pulls/
reviewees:
  dashboard: https://<%= ENV['WEB_DOMAIN'] %>/reviewees/dashboard
admins:
  reviews:
    show: https://<%= ENV['ADMIN_DOMAIN'] %>/admins/reviews/
links:
  home: https://<%= ENV['WEB_DOMAIN'] %>
  reviewer_repo_show: https://<%= ENV['REVIEWER_DOMAIN'] %>/reviewers/repos/
