top: https://<%= ENV['WEB_DOMAIN'] %>/
reviewers:
  dashbord: https://<%= ENV['REVIEWER_DOMAIN'] %>/dashboard
  sessions:
    new: http://<%= ENV['REVIEWER_DOMAIN'] %>/reviewers/sign_in
  pulls:
    show: https://<%= ENV['WEB_DOMAIN'] %>/reviewers/pulls/
links:
  home: https://<%= ENV['WEB_DOMAIN'] %>
  reviewer_repo_show: https://<%= ENV['WEB_DOMAIN'] %>/reviewers/repos/
